name: publish
'on':
  - push

jobs:
  build-C-servers:
    permissions: write-all
    name: Build C Servers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Tools
        run: |
          sudo apt upgrade
          sudo apt install build-essential cmake gdb -y
      - name: Build Code
        run: |
          cmake . && \
          cmake --build . --target all -j 10
      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: Servers_Docker
          path: ./Servers_Docker
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/mena97villalobos/servers:latest && \
          docker push ghcr.io/mena97villalobos/servers:latest

